spring:
  datasource:
    #    generate-unique-name: false
    #    name: tacocloud
    url: jdbc:h2:file:./data/tacocloud
    username: kienroro
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
